### ISSUE TITLE
Additional info in Read me file

### ISSUE THREAD

**Issue by Varda003** [Soumya-Kushwaha/SoundScape#38]
It is important that we add how one can contribute  in this project and some important features  about this project will also help.

**Comment by Varda003** [comment]
Please assign this issue to me I am well versed in creating documentation. Also @Soumya-Kushwaha don't forget to add GSSOC'24 label and Labels of Pr like Level 1 , 2 , 3

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!

**Comment by alishasingh06** [comment]
this content needs to be added in a separate file (contributing.md) and I'm ready to do that.
@Soumya-Kushwaha please assign this task to me and add labels.

**Comment by kavyagupta3011** [comment]
More contributing guidelines could be added to the readme file itself. Can you please assign this issue to me with the appropriate labels?

**Comment by Jhalak-Gupta** [comment]
I am interested in this task. Pls assign it to me under GSSOC'24 so that I can contribute to this project. I am good enough at my skills to complete this task efficiently.

**Comment by Taranpreet10451** [comment]
The readme file of this project is incomplete it doesn't contain many information like how to contribute and the Teckstack involved (the libraries used in the project).
It is really important to add the steps how to contribute in this project as it give ideas to beginners how to get involved in the contribution. 
I am capable enough to make the changes in the file accordingly please assign me this issue under GSSOC'24 so that I can give my contribution in this.

**Comment by SohaFarhana** [comment]
I would like to work on this issue
